bot.api-key: 1393065423:AAGsRbEXUkP5lpuOrJhfDDV1QqYX9bDWSmc

spring:
  datasource:
    url: jdbc:h2:mem:h2DB;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
